# Generated by Django 5.0.1 on 2024-05-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_historicalperformance_average_respose_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='fullFillMent_rate',
            new_name='fullfillment_rate',
        ),
    ]
